bindkey -e

zinit light-mode for \
       	zdharma-continuum/zinit-annex-as-monitor \
       	zdharma-continuum/zinit-annex-bin-gem-node \
       	zdharma-continuum/zinit-annex-patch-dl \
       	zdharma-continuum/zinit-annex-rust

zinit light-mode wait lucid silent for \
	z-shell/zsh-editing-workbench \
        zdharma/fast-syntax-highlighting \
        hlissner/zsh-autopair \
        ael-code/zsh-colored-man-pages \
        atload'_zsh_autosuggest_start' zsh-users/zsh-autosuggestions \
        atload'_zsh_autosuggest_start' zpm-zsh/colorize

zinit light-mode wait lucid silent is-snippet for \
        OMZ::plugins/urltools/urltools.plugin.zsh \
        PZT::modules/completion/init.zsh

[[ ! -f "$HOME/.cargo/env" ]] || source "$HOME/.cargo/env"
